AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: Serverless Order Processing System using Go and SAM

Resources:

  ## Queues, Tables, and Buckets
  OrderQueue:
    Type: AWS::SQS::Queue

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrdersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH

  ReceiptsBucket:
    Type: AWS::S3::Bucket

  ReceiveOrder:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./ReceiveOrder/template.yaml
      Parameters:
        OrdersTable: !Ref OrdersTable
        ReceiptsBucket: !Ref ReceiptsBucket

  ProcessOrder:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./ProcessOrder/template.yaml

  GetReceipt:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./GetReceipt/template.yaml
